default: &default
    root_url: https://localhost
    firefox_path: /usr/bin/firefox
    default_username: superman
    default_password: Admin123

development:
    <<: *default
    root_url: https://localhost
    headless: true

ci:
    <<: *default
    root_url: https://localhost
    headless: true

soak:
    <<: *default
    root_url: https://172.18.2.43
    headless: true
