default: &default
    root_url: https://localhost
    firefox_path: /usr/bin/firefox
    default_username: superman
    default_password: Admin123

development:
    <<: *default
    root_url: https://192.168.33.10
    firefox_path: /Applications/Firefox.app/Contents/MacOS/firefox
    headless: false

ci:
    <<: *default
    root_url: https://172.18.2.18
    headless: true